 
package de.xatc.controllerclient.gui.servercontrol;

import de.mytools.tools.swing.SwingTools;
import de.xatc.commons.networkpackets.atc.servercontrol.ShutdownServer;
import de.xatc.commons.networkpackets.atc.servercontrol.StartClientConnector;
import de.xatc.commons.networkpackets.atc.servercontrol.StartMQBroker;
import de.xatc.commons.networkpackets.atc.servercontrol.StartMessagingConsumers;
import de.xatc.commons.networkpackets.atc.servercontrol.StartMessagingProducers;
import de.xatc.commons.networkpackets.atc.servercontrol.StopClientConnector;
import de.xatc.commons.networkpackets.atc.servercontrol.StopMQBroker;
import de.xatc.commons.networkpackets.atc.servercontrol.StopMessagingConsumers;
import de.xatc.commons.networkpackets.atc.servercontrol.StopMessagingProducers;
import de.xatc.controllerclient.config.XHSConfig;

/**
 *
 * @author Mirko
 */


public class ServerControlFrame extends javax.swing.JFrame {

    /**
     * Creates new form ServerControlFrame
     */
    public ServerControlFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startClientConnectorButton = new javax.swing.JButton();
        stopClientConnectorButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        startMessageProducersButton = new javax.swing.JButton();
        stopMessageProducersButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        startMessagingConsumersButton = new javax.swing.JButton();
        stopMessagingConsumersButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        shutdownServerButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        startMQBrokerButton = new javax.swing.JButton();
        stopMQBrokerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(6, 3));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Server Control");
        getContentPane().add(jLabel1);
        getContentPane().add(jLabel7);
        getContentPane().add(jLabel8);

        jLabel2.setText("Startup Client Connector");
        getContentPane().add(jLabel2);

        startClientConnectorButton.setText("Client Connector Start");
        startClientConnectorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startClientConnectorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startClientConnectorButton);

        stopClientConnectorButton.setText("Client Connector Stop");
        stopClientConnectorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopClientConnectorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stopClientConnectorButton);

        jLabel3.setText("Startup Messaging Producers");
        getContentPane().add(jLabel3);

        startMessageProducersButton.setText("Message Producers Start");
        startMessageProducersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startMessageProducersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startMessageProducersButton);

        stopMessageProducersButton.setText("Message Producers Stop");
        stopMessageProducersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopMessageProducersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stopMessageProducersButton);

        jLabel4.setText("Startup Messaging Consumers");
        getContentPane().add(jLabel4);

        startMessagingConsumersButton.setText("Message Consumers Start");
        startMessagingConsumersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startMessagingConsumersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startMessagingConsumersButton);

        stopMessagingConsumersButton.setText("Message Consumers Stop");
        stopMessagingConsumersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopMessagingConsumersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stopMessagingConsumersButton);

        jLabel5.setText("Shutdown Server");
        getContentPane().add(jLabel5);

        shutdownServerButton.setText("Shutdown");
        shutdownServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shutdownServerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(shutdownServerButton);
        getContentPane().add(jLabel9);

        jLabel6.setText("Startup MQ Broker");
        getContentPane().add(jLabel6);

        startMQBrokerButton.setText("Start MQ Broker");
        startMQBrokerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startMQBrokerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startMQBrokerButton);

        stopMQBrokerButton.setText("Stop MQ Broker");
        stopMQBrokerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopMQBrokerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stopMQBrokerButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startClientConnectorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startClientConnectorButtonActionPerformed
        StartClientConnector s = new StartClientConnector();
        
        if (! isDataClientAvailable()) {
            return;
        }
        XHSConfig.getDataClient().writeMessage(s);
        
    }//GEN-LAST:event_startClientConnectorButtonActionPerformed

    private void stopClientConnectorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopClientConnectorButtonActionPerformed
       StopClientConnector s = new StopClientConnector();
        
        if (! isDataClientAvailable()) {
            return;
        }
        XHSConfig.getDataClient().writeMessage(s);
    }//GEN-LAST:event_stopClientConnectorButtonActionPerformed

    private void startMessageProducersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startMessageProducersButtonActionPerformed
        StartMessagingProducers s = new StartMessagingProducers();
        
        if (! isDataClientAvailable()) {
            return;
        }
        XHSConfig.getDataClient().writeMessage(s);
    }//GEN-LAST:event_startMessageProducersButtonActionPerformed

    private void stopMessageProducersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopMessageProducersButtonActionPerformed
         StopMessagingProducers s = new StopMessagingProducers();
        
        if (! isDataClientAvailable()) {
            return;
        }
        XHSConfig.getDataClient().writeMessage(s);
    }//GEN-LAST:event_stopMessageProducersButtonActionPerformed

    private void startMessagingConsumersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startMessagingConsumersButtonActionPerformed
         StartMessagingConsumers s = new StartMessagingConsumers();
        
        if (! isDataClientAvailable()) {
            return;
        }
        XHSConfig.getDataClient().writeMessage(s);
    }//GEN-LAST:event_startMessagingConsumersButtonActionPerformed

    private void stopMessagingConsumersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopMessagingConsumersButtonActionPerformed
        StopMessagingConsumers s = new StopMessagingConsumers();
        
        if (! isDataClientAvailable()) {
            return;
        }
        XHSConfig.getDataClient().writeMessage(s);
    }//GEN-LAST:event_stopMessagingConsumersButtonActionPerformed

    private void shutdownServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shutdownServerButtonActionPerformed
        ShutdownServer s = new ShutdownServer();
        
        if (! isDataClientAvailable()) {
            return;
        }
        XHSConfig.getDataClient().writeMessage(s);
    }//GEN-LAST:event_shutdownServerButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
        XHSConfig.setServerControlFrame(null);
        this.dispose();
        
    }//GEN-LAST:event_formWindowClosing

    private void startMQBrokerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startMQBrokerButtonActionPerformed
       StartMQBroker s = new StartMQBroker();
        
        if (! isDataClientAvailable()) {
            return;
        }
        XHSConfig.getDataClient().writeMessage(s);
    }//GEN-LAST:event_startMQBrokerButtonActionPerformed

    private void stopMQBrokerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopMQBrokerButtonActionPerformed
        StopMQBroker s = new StopMQBroker();
        
        if (! isDataClientAvailable()) {
            return;
        }
        XHSConfig.getDataClient().writeMessage(s);
    }//GEN-LAST:event_stopMQBrokerButtonActionPerformed

    private boolean isDataClientAvailable() {
        
        if (XHSConfig.getDataClient() == null) {
            SwingTools.alertWindow("DataClient is not available", this);
            return false;
        }
        return true;
    }
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton shutdownServerButton;
    private javax.swing.JButton startClientConnectorButton;
    private javax.swing.JButton startMQBrokerButton;
    private javax.swing.JButton startMessageProducersButton;
    private javax.swing.JButton startMessagingConsumersButton;
    private javax.swing.JButton stopClientConnectorButton;
    private javax.swing.JButton stopMQBrokerButton;
    private javax.swing.JButton stopMessageProducersButton;
    private javax.swing.JButton stopMessagingConsumersButton;
    // End of variables declaration//GEN-END:variables
}
