/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.xatc.flightplayer.gui;

import de.mytools.tools.swing.SwingTools;
import de.xatc.flightplayer.config.PlayerConfig;
import de.xatc.flightplayer.playerthread.PlayerControlThread;
import java.io.File;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author c047
 */
public class PlayerPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlayerPanel
     */
    public PlayerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        playerFilesList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        reloadButton = new javax.swing.JButton();
        atcServerAddressField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        atcServerPort = new javax.swing.JTextField();
        createAccountsCheckBox = new javax.swing.JCheckBox();
        doItButton = new javax.swing.JButton();
        abortButton = new javax.swing.JButton();
        intervalField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        progressPanel = new de.xatc.flightplayer.gui.ProgressPanel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setMaximumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(499, 499));

        jLabel1.setText("XPlane ATC Flight Plan Player");

        playerFilesList.setModel(fillPlayerFiles());
        jScrollPane2.setViewportView(playerFilesList);

        jLabel2.setText("Recorded Flights");

        reloadButton.setText("reload");
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });

        atcServerAddressField.setText("192.168.56.1");

        jLabel3.setText("ATC-.Server Data Address");

        jLabel4.setText("ATC-Server Data Port");

        atcServerPort.setText("9090");

        createAccountsCheckBox.setText("Generate UserAccounts by random?");

        doItButton.setText("do it!");
        doItButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doItButtonActionPerformed(evt);
            }
        });

        abortButton.setText("abort / close");

        intervalField.setText("(seconds)");
        intervalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intervalFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Interval");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reloadButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(abortButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(doItButton)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createAccountsCheckBox)
                            .addComponent(jLabel3)
                            .addComponent(atcServerAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(221, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(atcServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intervalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reloadButton)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atcServerAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atcServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intervalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(createAccountsCheckBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doItButton)
                    .addComponent(abortButton))
                .addGap(18, 18, 18)
                .addComponent(progressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed
        this.playerFilesList.setModel(this.fillPlayerFiles());
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_reloadButtonActionPerformed

    private void doItButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doItButtonActionPerformed
        
        if (this.playerFilesList.getSelectedIndices().length < 1) {
            SwingTools.alertWindow("No Files Selected", PlayerConfig.getMainFrame());
        }
        int interval =  0;
        if (StringUtils.isEmpty(this.intervalField.getText())) {
            interval = 5;
        }
        else if (this.intervalField.getText().equals("(seconds)")) {
            interval = 5;
        }
        else {
            interval = Integer.parseInt(this.intervalField.getText());
        }
        
        
        for (String s : this.playerFilesList.getSelectedValuesList()) {
            
            
            
            PlayerControlThread t = new PlayerControlThread(PlayerConfig.getRecordingDirectory() + File.separator + s,interval);
            t.start();
            
            
            
        }
        
        
    }//GEN-LAST:event_doItButtonActionPerformed

    private void intervalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intervalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intervalFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abortButton;
    private javax.swing.JTextField atcServerAddressField;
    private javax.swing.JTextField atcServerPort;
    private javax.swing.JCheckBox createAccountsCheckBox;
    private javax.swing.JButton doItButton;
    private javax.swing.JTextField intervalField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> playerFilesList;
    private de.xatc.flightplayer.gui.ProgressPanel progressPanel;
    private javax.swing.JButton reloadButton;
    // End of variables declaration//GEN-END:variables

    private DefaultListModel fillPlayerFiles() {

        DefaultListModel model = new DefaultListModel();
        
        List<File> fileList = SwingTools.getFilesAsList("recordings");
        
        for (File f : fileList) {
            
            model.add(0, f.getName());
        }
        
        
        return model;
        
        
    }

    public JButton getAbortButton() {
        return abortButton;
    }

    public void setAbortButton(JButton abortButton) {
        this.abortButton = abortButton;
    }

    public JTextField getAtcServerAddressField() {
        return atcServerAddressField;
    }

    public void setAtcServerAddressField(JTextField atcServerAddressField) {
        this.atcServerAddressField = atcServerAddressField;
    }

    public JTextField getAtcServerPort() {
        return atcServerPort;
    }

    public void setAtcServerPort(JTextField atcServerPort) {
        this.atcServerPort = atcServerPort;
    }

    public JCheckBox getCreateAccountsCheckBox() {
        return createAccountsCheckBox;
    }

    public void setCreateAccountsCheckBox(JCheckBox createAccountsCheckBox) {
        this.createAccountsCheckBox = createAccountsCheckBox;
    }

    public JButton getDoItButton() {
        return doItButton;
    }

    public void setDoItButton(JButton doItButton) {
        this.doItButton = doItButton;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JList<String> getjList1() {
        return jList1;
    }

    public void setjList1(JList<String> jList1) {
        this.jList1 = jList1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JList<String> getPlayerFilesList() {
        return playerFilesList;
    }

    public void setPlayerFilesList(JList<String> playerFilesList) {
        this.playerFilesList = playerFilesList;
    }

    public JButton getReloadButton() {
        return reloadButton;
    }

    public void setReloadButton(JButton reloadButton) {
        this.reloadButton = reloadButton;
    }

    public ProgressPanel getProgressPanel() {
        return progressPanel;
    }

    public void setProgressPanel(ProgressPanel progressPanel) {
        this.progressPanel = progressPanel;
    }

    
    
    
}
